build:
	protoc -I. --go_out=plugins=micro:. proto/consignment/consignment.proto
	GOOS=linux GOARCH=amd64 go build
	docker build -t shippy-service-consignment -f Dockerfile.fast .

run:
	docker run -p 50051:50051 shippy-service-consignment
